### ISSUE TITLE
Error: /inlang/[language].json is not prerenderable

### ISSUE THREAD

**Issue by babakar7** [inlang/inlang#1031]
## Problem  
Getting this error after build step: 
Error: /inlang/[language].json is not prerenderable
    at render_endpoint (file:///app/.svelte-kit/output/server/index.js:170:13)
    at resolve (file:///app/.svelte-kit/output/server/index.js:2600:28)
    at async handle2 (file:///app/.svelte-kit/output/server/chunks/hooks.server.js:32:10)
    at async respond (file:///app/.svelte-kit/output/server/index.js:2493:22)
    at async fetch (file:///app/.svelte-kit/output/server/index.js:2262:20)
    at async Object.fetch (file:///app/.svelte-kit/output/server/index.js:2201:12)
    at async file:///app/.svelte-kit/output/server/index.js:595:20
    at async file:///app/.svelte-kit/output/server/chunks/detectLanguage.js:44:24
Error: Not found: /inlang/en
    at resolve (file:///app/.svelte-kit/output/server/index.js:2620:18)
    at resolve (file:///app/.svelte-kit/output/server/index.js:2495:34)
    at resolve (file:///app/.svelte-kit/output/server/chunks/wrappers2.js:41:16)
    at handle2 (file:///app/.svelte-kit/output/server/chunks/hooks.server.js:32:16)
    at file:///app/.svelte-kit/output/server/chunks/wrappers2.js:73:19
    at apply_handle (file:///app/.svelte-kit/output/server/chunks/wrappers2.js:23:14)
    at resolve (file:///app/.svelte-kit/output/server/chunks/wrappers2.js:37:35)
    at file:///app/.svelte-kit/output/server/chunks/wrappers2.js:70:14
    at async respond (file:///app/.svelte-kit/output/server/index.js:2493:22)
    at async visit (file:///app/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:202:20)

## Steps to reproduce

This happens when i try to deploy my app with Github actions

3. ...

### Additional information

- `inlang.config.js` file:
/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
	const { default: jsonPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2/dist/index.js"
	)
	const { default: sdkPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.6.6/dist/index.js"
	)

	return {
		referenceLanguage: "en",
		plugins: [
			jsonPlugin({
				pathPattern: "./languages/{language}.json",
			}),
			sdkPlugin({
				languageNegotiation: {
					strategies: [
						{ type: "url" },
				]
				}
			}),
		],
	}
}

```js
// Please paste the file content here
```

- `npx @inlang/cli config validate` output:
✔ 🎉 Inlang config is valid!                                                              09:00:25
```sh
# Please paste the output here
```

- Browser: Chrome
<img width="1276" alt="Capture d’écran 2023-07-04 à 09 03 19" src="https://github.com/inlang/inlang/assets/40721549/8cf475c3-8508-40d8-be0a-8902232eaa2d">

- Operating system: MACOS
- Screenshots ?

**Comment by samuelstroschein** [comment]
@ivanhofer will look into this. 

FYI @babakar7, @ivanhofer is on vacation at the moment till next week. Response might take till next week.

**Comment by NilsJacobsen** [comment]
I would also recommend using the jsonPlugin from the monorepo. 
https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js

**Comment by samuelstroschein** [comment]
@babakar7, based on @NilsJacobsen plugin update remark, try the following config: 

```ts
/**
@type { import("@inlang/core/config").DefineConfig }
*/
export async function defineConfig(env) {
  const { default: jsonPlugin } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js"
  );
  const { default: sdkPlugin } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.6.6/dist/index.js"
  );

  return {
    referenceLanguage: "en",
    plugins: [
      jsonPlugin({
        pathPattern: "./languages/{language}.json",
      }),
      sdkPlugin({
        languageNegotiation: {
          strategies: [{ type: "url" }],
        },
      }),
    ],
  };
}

```

**Comment by babakar7** [comment]
Thank you Nils I was able to resolve the issue in the end. It was related to some other parts of my app I believe. Cheers
