### ISSUE TITLE
cannot read undefied reading frontmatter

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#282]
## Problem

From the server logs 

```

Jan 15 04:11:24 AM  TypeError: Cannot read properties of undefined (reading 'frontmatter')
Jan 15 04:11:24 AM      at Object.Head (file:///opt/render/project/src/source-code/website/dist/server/assets/*.page.564e2d38.js:20:49)
Jan 15 04:11:24 AM      at render (file:///opt/render/project/src/source-code/website/dist/server/assets/_default.page.server.064690cf.js:37:36)
Jan 15 04:11:24 AM      at <anonymous> (/opt/render/project/src/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage/renderPageContext.js:178:65)
Jan 15 04:11:24 AM      at <anonymous> (/opt/render/project/src/node_modules/vite-plugin-ssr/dist/cjs/utils/callHookWithTimeout.js:34:31)
Jan 15 04:11:24 AM      at callHookWithTimeout (/opt/render/project/src/node_modules/vite-plugin-ssr/dist/cjs/utils/callHookWithTimeout.js:40:5)
Jan 15 04:11:24 AM      at executeRenderHook (/opt/render/project/src/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage/renderPageContext.js:178:38)
Jan 15 04:11:24 AM      at renderPageContext (/opt/render/project/src/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage/renderPageContext.js:64:36)
Jan 15 04:11:24 AM      at renderPage (/opt/render/project/src/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:21:16)
Jan 16 05:06:25 AM  TypeError: Cannot read properties of undefined (reading 'frontmatter')

```

### Expected behavior

Not crashing

**Comment by samuelstroschein** [comment]
still exists. probably good to switch render to `renderAsync` and get markdown files via `createResource`

**Comment by samuelstroschein** [comment]
Reproduction: 

https://user-images.githubusercontent.com/35429197/215873363-f33b0c43-3d08-439b-a9db-f137fe01d423.mp4
