### ISSUE TITLE
CLI has no access to `env`/`fetch`

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#777]
## Problem

```sh
felixhaberle@MBP-von-Felix ~/D/g/i/s/s/s/a/e/test-app (cli-machine-translation) [1]> npx @inlang/cli@0.8.1 ma
chine translate
Need to install the following packages:
  @inlang/cli@0.8.1
Ok to proceed? (y) y
ℹ ✅ Using inlang config file at /Users/felixhaberle/Desktop/git/inlang/source-code/sdk-js/src/adapter-sveltekit/examples/test-app/inlang.config.js
ℹ 🌏 Found 5 languages with a total of 13 messages.                                                11:58:58
ℹ 📝 Translating to 4 languages. [de, es, pt]                                                      11:58:58

 WARN  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:


 ERROR  TypeError: fetch failed                                                                    11:58:58
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async n (file:///Users/felixhaberle/.npm/_npx/fc79f29e9d589708/node_modules/@inlang/cli/dist/main.js:24:56689)
    at async Ko.W5 (file:///Users/felixhaberle/.npm/_npx/fc79f29e9d589708/node_modules/@inlang/cli/dist/main.js:242:1750)
```

### Expected behavior

Should work 😅

## Steps to reproduce

`npx @inlang/cli@0.8.1 machine translate`

<img width="789" alt="Bildschirmfoto 2023-05-17 um 12 34 03" src="https://github.com/inlang/inlang/assets/34959078/316a78c8-2adc-4a2b-9b16-f4002d0fcd7f">

**Comment by felixhaeberle** [comment]
Additional info to debug: For fetch to trigger, you have to set an untranslated key in the reference resource which is not present in another resource (any other language).

**Comment by samuelstroschein** [comment]
Fixed by all the commits above jesus.
